# Generated by Django 5.2.7 on 2026-01-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.CharField(db_column='IdMaquina', max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='MaquinaD', max_length=255)),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'db_table': 'TMAN010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VTMan',
            fields=[
                ('id_orden', models.BigIntegerField(db_column='IDORDEN', primary_key=True, serialize=False)),
                ('id_concepto', models.CharField(db_column='IDCONCEPTO', max_length=50)),
                ('hora_inicio', models.DateTimeField(blank=True, db_column='HORA_D', null=True)),
                ('hora_fin', models.DateTimeField(blank=True, db_column='HORA_H', null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='FECHA', null=True)),
                ('id_maquina', models.CharField(blank=True, db_column='IDMAQUINA', max_length=50, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='OBS', max_length=255, null=True)),
                ('id_operacion', models.CharField(blank=True, db_column='IDOPERACION', max_length=50, null=True)),
                ('tiempo_cotizado_individual', models.FloatField(blank=True, db_column='Tiempo_cotizado_individual', null=True)),
                ('cantidad_producida', models.FloatField(blank=True, db_column='Cantidad_producida', null=True)),
                ('tiempo_minutos', models.FloatField(blank=True, db_column='Tiempo_minutos', null=True)),
                ('tiempo_cotizado', models.FloatField(blank=True, db_column='Tiempo_cotizado', null=True)),
                ('es_programado', models.BooleanField(blank=True, db_column='Es_programado', null=True)),
                ('es_no_programado', models.BooleanField(blank=True, db_column='Es_No_Programado', null=True)),
                ('es_interrupcion', models.BooleanField(blank=True, db_column='Es_interrupcion', null=True)),
                ('es_proceso', models.BooleanField(blank=True, db_column='Es_proceso', null=True)),
                ('formula', models.CharField(blank=True, db_column='Formula', max_length=100, null=True)),
                ('articulo', models.CharField(blank=True, db_column='Articulo', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Vista Tiempos Manufactura',
                'verbose_name_plural': 'Vistas Tiempos Manufactura',
                'db_table': 'V_TMAN',
                'managed': False,
            },
        ),
    ]
