# Generated by Django 5.2.7 on 2026-01-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_maquina', models.CharField(max_length=50, unique=True, verbose_name='ID de Máquina (Código)')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Descriptivo')),
                ('horario_inicio_sem', models.TimeField(default='07:00', verbose_name='Inicio Lun-Vie')),
                ('horario_fin_sem', models.TimeField(default='16:00', verbose_name='Fin Lun-Vie')),
                ('trabaja_sabado', models.BooleanField(default=False)),
                ('horario_inicio_sab', models.TimeField(blank=True, null=True, verbose_name='Inicio Sábado')),
                ('horario_fin_sab', models.TimeField(blank=True, null=True, verbose_name='Fin Sábado')),
                ('trabaja_domingo', models.BooleanField(default=False)),
                ('horario_inicio_dom', models.TimeField(blank=True, null=True, verbose_name='Inicio Domingo')),
                ('horario_fin_dom', models.TimeField(blank=True, null=True, verbose_name='Fin Domingo')),
            ],
            options={
                'verbose_name': 'Configuración de Máquina',
                'verbose_name_plural': 'Configuraciones de Máquinas',
                'db_table': 'maquina_config',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='maquina',
            options={'managed': False, 'verbose_name': 'Maquina SQL Server', 'verbose_name_plural': 'Maquinas SQL Server'},
        ),
    ]
