# Generated by Django 5.2.7 on 2026-01-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_maquinaconfig_alter_maquina_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaconfig',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa en Tablero'),
        ),
    ]
