# Generated by Django 5.2.7 on 2026-01-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_maquinaconfig_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperarioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=50, unique=True, verbose_name='Legajo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('sector', models.CharField(default='PRODUCCION', max_length=100, verbose_name='Sector')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Configuración de Operario',
                'verbose_name_plural': 'Configuraciones de Operarios',
                'db_table': 'operario_config',
                'managed': True,
            },
        ),
    ]
