# Generated by Django 5.2.7 on 2026-01-14 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_operarioconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CORRECTIVO', 'Correctivo (Rotura)'), ('PREVENTIVO', 'Preventivo (Programado)'), ('MEJORA', 'Mejora / Instalación')], default='CORRECTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Pendiente / Averiada'), ('PROCESO', 'En Reparación'), ('CERRADO', 'Reparada / Finalizada')], default='ABIERTO', max_length=20)),
                ('descripcion_falla', models.TextField(verbose_name='Descripción de la Falla')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_reparacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tecnico_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones_tecnicas', models.TextField(blank=True, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='dashboard.maquinaconfig')),
            ],
            options={
                'verbose_name': 'Incidencia de Mantenimiento',
                'verbose_name_plural': 'Incidencias de Mantenimiento',
                'db_table': 'mantenimiento_incidencias',
                'managed': True,
            },
        ),
    ]
