# Generated by Django 5.2.7 on 2026-01-14 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_reporte',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Reporte/Falla'),
        ),
    ]
