# Generated by Django 5.2.7 on 2026-01-16 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_mantenimiento_fecha_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('modelo', models.CharField(max_length=50, verbose_name='Entidad Afectada')),
                ('referencia_id', models.CharField(max_length=100, verbose_name='ID Referencia')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=20)),
                ('detalle', models.TextField(verbose_name='Detalle del Cambio')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'audit_log_cambios',
                'ordering': ['-fecha'],
                'managed': True,
            },
        ),
    ]
