# Generated by Django 5.2.7 on 2026-01-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinaconfig',
            name='trabaja_domingo',
        ),
        migrations.AddField(
            model_name='maquinaconfig',
            name='fecha_ultimo_preventivo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Último Service'),
        ),
        migrations.AddField(
            model_name='maquinaconfig',
            name='frecuencia_preventivo_horas',
            field=models.IntegerField(default=0, help_text='0 = Desactivado', verbose_name='Frecuencia Service (Hs)'),
        ),
    ]
