# Generated by Django 5.2.7 on 2026-01-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_maquinaconfig_trabaja_domingo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaconfig',
            name='fecha_proximo_preventivo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Próximo Service (Agenda)'),
        ),
    ]
