# Generated by Django 5.2.7 on 2026-01-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_maquinaconfig_fecha_proximo_preventivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaconfig',
            name='pos_x',
            field=models.FloatField(default=0.0, verbose_name='Posición X (%)'),
        ),
        migrations.AddField(
            model_name='maquinaconfig',
            name='pos_y',
            field=models.FloatField(default=0.0, verbose_name='Posición Y (%)'),
        ),
    ]
