# Generated by Django 5.2.7 on 2026-01-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_maquinaconfig_pos_x_maquinaconfig_pos_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinaconfig',
            name='activa',
        ),
        migrations.AddField(
            model_name='maquinaconfig',
            name='dim_height',
            field=models.FloatField(default=4.0, verbose_name='Alto (%)'),
        ),
        migrations.AddField(
            model_name='maquinaconfig',
            name='dim_width',
            field=models.FloatField(default=4.0, verbose_name='Ancho (%)'),
        ),
        migrations.AddField(
            model_name='maquinaconfig',
            name='proceso_predeterminado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proceso Default'),
        ),
        migrations.AddField(
            model_name='maquinaconfig',
            name='rotacion',
            field=models.FloatField(default=0.0, verbose_name='Rotación (Grados)'),
        ),
        migrations.AddField(
            model_name='maquinaconfig',
            name='tipo_maquina',
            field=models.CharField(choices=[('GENERICO', 'Genérico (Círculo)'), ('CNC', 'CNC (Cuadrado)'), ('TORNO', 'Torno (Rectángulo)'), ('AGUJEREADORA', 'Agujereadora (Rectángulo)'), ('ROBOT', 'Robot (Círculo)'), ('PRENSA', 'Prensa (Rectángulo)')], default='GENERICO', max_length=20, verbose_name='Tipo de Máquina'),
        ),
    ]
