# Generated by Django 5.2.7 on 2026-01-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_maquinaconfig_activa_maquinaconfig_dim_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaconfig',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
