# Generated by Django 5.2.7 on 2026-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_maquinaconfig_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaconfig',
            name='border_weight',
            field=models.FloatField(default=2.0, verbose_name='Grosor Línea (px)'),
        ),
        migrations.AddField(
            model_name='maquinaconfig',
            name='label_size',
            field=models.FloatField(default=13.0, verbose_name='Tamaño Letra (px)'),
        ),
    ]
