# Generated by Django 5.2.7 on 2026-01-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_maquinaconfig_border_weight_maquinaconfig_label_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaconfig',
            name='visible_en_mapa',
            field=models.BooleanField(default=True, verbose_name='Visible en Mapa'),
        ),
    ]
