# Generated by Django 5.2.7 on 2026-01-29 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_maquinaconfig_visible_en_mapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='DETENCION_CRITICA', max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_notificacion_ext', models.DateTimeField(blank=True, null=True, verbose_name='Enviado a WA/TG')),
                ('resuelta', models.BooleanField(default=False)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.maquinaconfig', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Historial de Alerta',
                'verbose_name_plural': 'Historial de Alertas',
                'db_table': 'alerta_historial',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
