# Generated by Django 5.2.7 on 2026-01-30 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alertahistorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MYSQL', 'Base de Datos MySQL'), ('COMPLETO', 'Sistema Completo (DB + Código)')], default='COMPLETO', max_length=20)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('ERROR', 'Error'), ('RESTAURADO', 'Restaurado')], default='EXITOSO', max_length=20)),
                ('archivo_db', models.CharField(blank=True, max_length=255, null=True, verbose_name='Archivo DB')),
                ('archivo_codigo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Archivo Código')),
                ('tamano_db_mb', models.FloatField(default=0.0, verbose_name='Tamaño DB (MB)')),
                ('tamano_codigo_mb', models.FloatField(default=0.0, verbose_name='Tamaño Código (MB)')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Historial de Backup',
                'verbose_name_plural': 'Historial de Backups',
                'db_table': 'backup_historial',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
