# Generated by Django 5.2.7 on 2026-02-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_backuphistorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token del Bot de Telegram')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Chat de Telegram')),
                ('activar_telegram', models.BooleanField(default=False, verbose_name='Activar Notificaciones Telegram')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono WhatsApp (Formato Int.)')),
                ('whatsapp_apikey', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Key WhatsApp')),
                ('activar_whatsapp', models.BooleanField(default=False, verbose_name='Activar Notificaciones WhatsApp')),
                ('minutos_detencion_critica', models.IntegerField(default=20, verbose_name='Minutos para Alerta de Detención')),
                ('alertar_mantenimiento', models.BooleanField(default=True, verbose_name='Alertar Apertura de Mantenimiento')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'db_table': 'notificacion_config',
                'managed': True,
            },
        ),
    ]
