# Generated by Django 5.2.7 on 2026-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_notificacionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaconfig',
            name='trabaja_domingo',
            field=models.BooleanField(default=False),
        ),
    ]
