# Generated by Django 5.2.7 on 2026-02-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_maquinaconfig_trabaja_domingo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertahistorial',
            options={'verbose_name': 'Historial de Alerta'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de Auditoría', 'verbose_name_plural': 'Registros de Auditoría'},
        ),
        migrations.AlterModelOptions(
            name='backuphistorial',
            options={'verbose_name': 'Historial de Backup'},
        ),
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'verbose_name': 'Incidencia de Mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='maquinaconfig',
            options={'verbose_name': 'Configuración de Máquina', 'verbose_name_plural': 'Configuraciones de Máquinas'},
        ),
        migrations.AlterModelOptions(
            name='notificacionconfig',
            options={'verbose_name': 'Configuración de Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='operarioconfig',
            options={'verbose_name': 'Configuración de Operario'},
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='observaciones_tecnicas',
            field=models.TextField(blank=True, db_column='observaciones_tecnicas', null=True),
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='observaciones_tecnicas',
            new_name='detalle_resolucion',
        ),
        migrations.RemoveField(
            model_name='alertahistorial',
            name='maquina',
        ),
        migrations.AddField(
            model_name='alertahistorial',
            name='maquina_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operarioconfig',
            name='en_vacaciones',
            field=models.BooleanField(default=False, verbose_name='En Vacaciones'),
        ),
        migrations.AlterField(
            model_name='alertahistorial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='alertahistorial',
            name='fecha_notificacion_ext',
            field=models.DateTimeField(blank=True, db_column='fecha_notificacion_ext', null=True),
        ),
        migrations.AlterField(
            model_name='alertahistorial',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], default='UPDATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del Cambio'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='modelo',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Entidad Afectada'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='referencia_id',
            field=models.CharField(default='0', max_length=100, verbose_name='ID Referencia'),
        ),
        migrations.AlterField(
            model_name='backuphistorial',
            name='archivo_codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backuphistorial',
            name='archivo_db',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backuphistorial',
            name='estado',
            field=models.CharField(default='EXITOSO', max_length=20),
        ),
        migrations.AlterField(
            model_name='backuphistorial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='backuphistorial',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backuphistorial',
            name='tamano_codigo_mb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='backuphistorial',
            name='tamano_db_mb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='backuphistorial',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='backuphistorial',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion_falla',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_reporte',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(default='CORRECTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='maquinaconfig',
            name='fecha_proximo_preventivo',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Preventivo'),
        ),
        migrations.AlterField(
            model_name='maquinaconfig',
            name='fecha_ultimo_preventivo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Preventivo'),
        ),
        migrations.AlterField(
            model_name='maquinaconfig',
            name='frecuencia_preventivo_horas',
            field=models.IntegerField(default=0, verbose_name='Frecuencia Preventiva (Horas)'),
        ),
        migrations.AlterField(
            model_name='notificacionconfig',
            name='activar_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacionconfig',
            name='activar_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacionconfig',
            name='alertar_mantenimiento',
            field=models.BooleanField(default=True, verbose_name='Alertar Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='notificacionconfig',
            name='minutos_detencion_critica',
            field=models.IntegerField(default=60, verbose_name='Mins para Alerta Detención Crítica'),
        ),
        migrations.AlterField(
            model_name='notificacionconfig',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chat ID Telegram'),
        ),
        migrations.AlterField(
            model_name='notificacionconfig',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Bot Telegram'),
        ),
        migrations.AlterField(
            model_name='notificacionconfig',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, db_column='ultima_modificacion'),
        ),
        migrations.AlterField(
            model_name='notificacionconfig',
            name='whatsapp_apikey',
            field=models.CharField(blank=True, db_column='whatsapp_apikey', max_length=255, null=True, verbose_name='API Key WhatsApp'),
        ),
        migrations.AlterField(
            model_name='notificacionconfig',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Destino WhatsApp'),
        ),
        migrations.AlterField(
            model_name='operarioconfig',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='operarioconfig',
            name='legajo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Legajo (ID ERP)'),
        ),
        migrations.AlterField(
            model_name='operarioconfig',
            name='sector',
            field=models.CharField(default='PRODUCCION', max_length=50),
        ),
    ]
