# Generated by Django 5.2.7 on 2026-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_alertahistorial_options_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionconfig',
            name='dias_atras_auditoria',
            field=models.IntegerField(default=1, verbose_name='Días hacia atrás para auditar anomalías'),
        ),
    ]
