# Generated by Django 5.2.11 on 2026-06-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_notificacionconfig_dias_atras_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaconfig',
            name='tipo_maquina',
            field=models.CharField(choices=[('GENERICO', 'Genérico (Círculo)'), ('CNC', 'CNC (Cuadrado)'), ('TORNO', 'Torno (Rectángulo)'), ('AGUJEREADORA', 'Agujereadora (Rectángulo)'), ('ROBOT', 'Robot (Círculo)'), ('PRENSA', 'Prensa (Rectángulo)'), ('BANCO SOLDADURA', 'Banco Soldadura (Rectángulo)'), ('BANCO TRABAJO', 'Banco Trabajo (Rectángulo)'), ('BANCO PULIDO', 'Banco Pulido (Rectángulo)')], default='GENERICO', max_length=20, verbose_name='Tipo de Máquina'),
        ),
    ]
