# Generated by Django 5.2.11 on 2026-06-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_maquinaconfig_tipo_maquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic Claude')], default='gemini', max_length=20, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuración de Proveedor IA',
                'db_table': 'ai_provider_config',
            },
        ),
    ]
